# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `bundle-audit` gem.
# Please instead update this file by running `bin/tapioca gem bundle-audit`.

# source://bundle-audit-0.1.0/lib/bundle/audit/version.rb:1
module Bundle; end

# source://bundle-audit-0.1.0/lib/bundle/audit/version.rb:2
module Bundle::Audit; end

# source://bundle-audit-0.1.0/lib/bundle/audit/version.rb:3
Bundle::Audit::VERSION = T.let(T.unsafe(nil), String)
