# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/jekyll-coffeescript/all/jekyll-coffeescript.rbi
#
# jekyll-coffeescript-2.0.0

module Jekyll
end
module Jekyll::Coffeescript
end
module Jekyll::Converters
end
class Jekyll::Converters::CoffeeScript < Jekyll::Converter
  def convert(content); end
  def matches(ext); end
  def output_ext(_ext); end
  def self.inherited(const_); end
  def setup; end
end
