# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/jekyll-optional-front-matter/all/jekyll-optional-front-matter.rbi
#
# jekyll-optional-front-matter-0.3.2

module JekyllOptionalFrontMatter
end
class JekyllOptionalFrontMatter::Generator < Jekyll::Generator
  def blacklisted?(page); end
  def cleanup?; end
  def disabled?; end
  def entry_filter; end
  def generate(site); end
  def initialize(site); end
  def markdown_converter; end
  def markdown_files; end
  def option(key); end
  def page_from_static_file(static_file); end
  def pages; end
  def pages_to_add; end
  def self.inherited(const_); end
  def site; end
  def site=(arg0); end
  def static_files_to_remove; end
  def whitelisted?(page); end
end
