# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/jekyll-readme-index/all/jekyll-readme-index.rbi
#
# jekyll-readme-index-0.3.0

module JekyllReadmeIndex
end
class JekyllReadmeIndex::Generator < Jekyll::Generator
  def cleanup?; end
  def dir_has_index?(relative_path); end
  def disabled?; end
  def generate(site); end
  def initialize(site); end
  def markdown_converter; end
  def option(key); end
  def readme_regex; end
  def readmes; end
  def readmes_with_frontmatter; end
  def self.inherited(const_); end
  def should_be_index?(readme); end
  def site; end
  def site=(arg0); end
  def with_frontmatter?; end
end
module Jekyll
end
class Jekyll::StaticFile
  def to_page; end
end
class Jekyll::Page
  def update_permalink; end
end
