# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/jekyll-watch/all/jekyll-watch.rbi
#
# jekyll-watch-2.2.1

module Jekyll
end
module Jekyll::Watch
end
module Jekyll::Watcher
  def build_listener(site, options); end
  def config_files(options); end
  def custom_excludes(options); end
  def listen_handler(site); end
  def listen_ignore_paths(options); end
  def normalize_encoding(obj, desired_encoding); end
  def process(site, time); end
  def sleep_forever; end
  def to_exclude(options); end
  def watch(options, site = nil); end
  extend Jekyll::Watcher
end
module Jekyll::Commands
end
module Jekyll::Commands::Watch
  def init_with_program(prog); end
  def process(options); end
  extend Jekyll::Commands::Watch
end
