# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/jekyll-commonmark/all/jekyll-commonmark.rbi
#
# jekyll-commonmark-1.4.0

module Jekyll
end
module Jekyll::Converters
end
class Jekyll::Converters::Markdown < Jekyll::Converter
end
class Jekyll::Converters::Markdown::CommonMark
  def convert(content); end
  def initialize(config); end
  def setup_extensions(config); end
  def setup_options(config, parse_keys, render_keys); end
  def validate(list, bucket, type); end
end
