# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/jekyll-mentions/all/jekyll-mentions.rbi
#
# jekyll-mentions-1.6.0

module Jekyll
end
class Jekyll::Mentions
  def self.default_mention_base; end
  def self.filter_regex; end
  def self.filter_with_mention(src); end
  def self.filters; end
  def self.mention_base(config = nil); end
  def self.mention_username_pattern; end
  def self.mentionable?(doc); end
  def self.mentionify(doc); end
end
class Jekyll::Mentions::InvalidJekyllMentionConfig < Jekyll::Errors::FatalException
end
