# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/jekyll-titles-from-headings/all/jekyll-titles-from-headings.rbi
#
# jekyll-titles-from-headings-0.5.3

module JekyllTitlesFromHeadings
end
class JekyllTitlesFromHeadings::Generator < Jekyll::Generator
  def collections?; end
  def disabled?; end
  def filters; end
  def generate(site); end
  def inferred_title?(document); end
  def initialize(site); end
  def markdown?(document); end
  def markdown_converter; end
  def option(key); end
  def self.inherited(const_); end
  def should_add_title?(document); end
  def site; end
  def site=(arg0); end
  def strip_markup(string); end
  def strip_title!(document); end
  def strip_title?(document); end
  def strip_title_excerpt!(document); end
  def strip_title_excerpt?(document); end
  def title?(document); end
  def title_for(document); end
end
