# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/jekyll-paginate/all/jekyll-paginate.rbi
#
# jekyll-paginate-1.1.0

module Jekyll
end
module Jekyll::Paginate
end
class Jekyll::Paginate::Pager
  def initialize(site, page, all_posts, num_pages = nil); end
  def next_page; end
  def next_page_path; end
  def page; end
  def per_page; end
  def posts; end
  def previous_page; end
  def previous_page_path; end
  def self.calculate_pages(all_posts, per_page); end
  def self.ensure_leading_slash(path); end
  def self.in_hierarchy(source, page_dir, paginate_path); end
  def self.paginate_path(site, num_page); end
  def self.pagination_candidate?(config, page); end
  def self.pagination_enabled?(site); end
  def self.remove_leading_slash(path); end
  def to_liquid; end
  def total_pages; end
  def total_posts; end
end
class Jekyll::Paginate::Pagination < Jekyll::Generator
  def generate(site); end
  def paginate(site, page); end
  def self.first_page_url(site); end
  def self.inherited(const_); end
  def template_page(site); end
end
