# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `manpages` gem.
# Please instead update this file by running `bin/tapioca gem manpages`.

# source://manpages-0.6.1/lib/manpages/version.rb:1
module Manpages; end

# source://manpages-0.6.1/lib/manpages/gem_version.rb:2
class Manpages::GemVersion
  # @return [GemVersion] a new instance of GemVersion
  #
  # source://manpages-0.6.1/lib/manpages/gem_version.rb:3
  def initialize(gem_spec); end

  # @return [Boolean]
  #
  # source://manpages-0.6.1/lib/manpages/gem_version.rb:7
  def latest?; end

  private

  # source://manpages-0.6.1/lib/manpages/gem_version.rb:17
  def all_gem_versions; end

  # source://manpages-0.6.1/lib/manpages/gem_version.rb:13
  def latest_gem; end
end

# source://manpages-0.6.1/lib/manpages/install.rb:4
class Manpages::Install
  # @return [Install] a new instance of Install
  #
  # source://manpages-0.6.1/lib/manpages/install.rb:5
  def initialize(gem_spec, gem_dir, target_dir); end

  # source://manpages-0.6.1/lib/manpages/install.rb:11
  def install_manpages; end

  private

  # source://manpages-0.6.1/lib/manpages/install.rb:23
  def link_manpage(file); end

  # source://manpages-0.6.1/lib/manpages/install.rb:17
  def link_manpages; end
end

# source://manpages-0.6.1/lib/manpages/man_files.rb:4
class Manpages::ManFiles
  # @return [ManFiles] a new instance of ManFiles
  #
  # source://manpages-0.6.1/lib/manpages/man_files.rb:7
  def initialize(gem_dir, target_dir = T.unsafe(nil)); end

  # Returns the value of attribute man_dir.
  #
  # source://manpages-0.6.1/lib/manpages/man_files.rb:5
  def man_dir; end

  # source://manpages-0.6.1/lib/manpages/man_files.rb:24
  def man_file_path(file); end

  # source://manpages-0.6.1/lib/manpages/man_files.rb:16
  def manpages; end

  # @return [Boolean]
  #
  # source://manpages-0.6.1/lib/manpages/man_files.rb:12
  def manpages_present?; end
end

# source://manpages-0.6.1/lib/manpages/uninstall.rb:2
class Manpages::Uninstall
  # @return [Uninstall] a new instance of Uninstall
  #
  # source://manpages-0.6.1/lib/manpages/uninstall.rb:3
  def initialize(gem_spec, gem_dir, target_dir); end

  # source://manpages-0.6.1/lib/manpages/uninstall.rb:9
  def uninstall_manpages; end

  private

  # source://manpages-0.6.1/lib/manpages/uninstall.rb:21
  def unlink_manpage(file); end

  # source://manpages-0.6.1/lib/manpages/uninstall.rb:15
  def unlink_manpages; end
end

# source://manpages-0.6.1/lib/manpages/version.rb:2
Manpages::VERSION = T.let(T.unsafe(nil), String)
