# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/rinku/all/rinku.rbi
#
# rinku-2.0.6

module Rinku
  def auto_link(*arg0); end
  def self.auto_link(*arg0); end
  def self.skip_tags; end
  def self.skip_tags=(arg0); end
end
