data-update:
- changed-files:
  - any-glob-to-any-file: '_data/**'

text-update:
- changed-files:
  - any-glob-to-any-file: '**/*.md'

tool-update:
- changed-files:
  - any-glob-to-any-file: '_tools/**'

code-update:
- changed-files:
  - any-glob-to-any-file:
    - '**/*.rb'
    - 'Gemfile'
    - 'Rakefile'
    - '_config.yml'
    - '.*'
