# Use this file to configure the Overcommit hooks you wish to use. This will
# extend the default configuration defined in:
# https://github.com/sds/overcommit/blob/master/config/default.yml
#
# At the topmost level of this YAML file is a key representing type of hook
# being run (e.g. pre-commit, commit-msg, etc.). Within each type you can
# customize each hook, such as whether to only run it on certain files (via
# `include`), whether to only display output if it fails (via `quiet`), etc.
#
# For a complete list of hooks, see:
# https://github.com/sds/overcommit/tree/master/lib/overcommit/hook
#
# For a complete list of options that you can use to customize hooks, see:
# https://github.com/sds/overcommit#configuration
#
# Uncomment the following lines to make the configuration take effect.

PreCommit:
  SpellCheck:
    enabled: true

  RakeTarget:
    enabled: true
    targets:
      - precommit

  RuboCop:
    enabled: true

  TrailingWhitespace:
    enabled: true

  Mdl:
    enabled: true
    exclude: _site

  YamlSyntax:
    enabled: true

  BundleAudit:
    enabled: true
  BundleCheck:
    enabled: true
  BundleOutdated:
    enabled: true

PostRewrite:
  BundleInstall:
    enabled: true

PostCheckout:
  IndexTags:
    enabled: true # Generate a tags file with `ctags` exach time HEAD changes

  BundleInstall:
    enabled: true

  SubmoduleStatus:
    enabled: true

PostMerge:
  SubmoduleStatus:
    enabled: true
