# frozen_string_literal: true

source 'https://rubygems.org'

gemspec

group :development, :test do
  gem 'pry'
  gem 'rake'
  gem 'rbs'
  gem 'rbs-inline'
  gem 'rspec'
  gem 'rubocop', require: false
  gem 'rubocop-rake'
  gem 'rubocop-rspec'
  gem 'steep'
end
