# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::BASE_PATH; end
module RuboCop::Cop::AllowedMethods::Config; end
module TIPW::TIPWCodenames::WikiCloth::Parser; end
