name: Continuous Integration

on:
  pull_request:
    branches: [ main ]

jobs:
  ci-test:
    name: "Root Project"
    uses: ./.github/workflows/build-test.yml

  ci-build-jekyll:
    name: "Jekyll"
    needs: ci-test
    uses: ./.github/workflows/build-jekyll.yml

  ci-build-python:
    name: "Python"
    needs: ci-test
    uses: ./.github/workflows/build-python.yml

  ci-build-ruby:
    name: "Ruby"
    needs: ci-test
    uses: ./.github/workflows/build-ruby.yml

  ci-build-node:
    name: "Node"
    needs: ci-test
    uses: ./.github/workflows/build-node.yml
