name: Continuous Integration - Node Package

on:
  workflow_call:
    inputs:
      # Counterintuitive, but this is the value for full history required for rev-list --count
      fetch-depth:
        default: 0
        required: false
        type: number

jobs:
  ci-test-node:
    name: Perform Node CI Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: ["22", "24"]

    defaults:
      run:
        working-directory: ./_packages/node

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: ${{ inputs.fetch-depth }}

      - uses: oven-sh/setup-bun@v2

      - uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node Packages
        uses: actions/cache@v5
        with:
          path: _packages/node/node_modules
          key: ${{ runner.os }}-build-ci-node-${{ matrix.node-version }}-${{ hashFiles('_packages/node/bun.lock') }}

      - name: Install dependencies
        run: bun install

      - name: Perform a Build
        run: bun run build

      - name: Run Package Tests
        run: bun run test

      - name: Package Node Artifact
        run: bun pm pack

      - name: Archive Node Package Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: package-node-${{ matrix.node-version }}
          path: _packages/node/*.tgz
