name: Static Website - Build

on:
  push:
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: publish-site
  cancel-in-progress: false

jobs:
  ci-build-jekyll:
    uses: ./.github/workflows/build-jekyll.yml

  github-pages:
    name: Publish Static Website
    runs-on: ubuntu-latest
    needs: ci-build-jekyll
    environment: gh-pages
    permissions:
      contents: write

    steps:
      - name: Download Site Artifacts
        uses: actions/download-artifact@v5
        with:
          name: data-ci-site
          path: _site

      - name: Publish to gh-pages Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./_site
          cname: docs.hackdiffe.rent
