name: Publish Package - Python / PyPI

on:
  push:
    branches: [ main ]

jobs:
  ci-build-python:
    uses: ./.github/workflows/build-python.yml

  publish-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: ci-build-python
    environment: pypi-push
    permissions:
      contents: read
      # Required for PyPI trusted publishing (OIDC)
      id-token: write

    steps:
      - name: Download Python Package Artifacts
        uses: actions/download-artifact@v5
        with:
          name: package-python-3.12
          path: dist

      - name: Publish to PyPI
        # Note: No "password" or "api-token" secret is referenced here, this uses trusted publishing
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
