name: Periodic Updates

on:
  schedule:
    - cron: '17 8 * * *'

  workflow_dispatch:
    inputs:
      ref:
        default: 'auto-update-bot'
        required: false
        type: string

concurrency:
  group: periodic-update
  cancel-in-progress: false

env:
  UPDATE_BRANCH: ${{ inputs.ref || 'auto-update-bot' }}

jobs:
  periodic-update:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Install OS Packages
        run: sudo apt-get update && sudo apt-get install -y libidn-dev cmake

      # This allows us to continue to update an existing auto-update branch if it has yet to be merged, but if one
      # does not exist we will create a new one from the main branch.
      - id: repo
        shell: bash
        run: |
          if git ls-remote --heads --quiet --exit-code "https://github.com/${{ github.repository }}.git" "${UPDATE_BRANCH}"
          then
            echo "::notice::Checkout: ${{ github.repository }} using ${UPDATE_BRANCH}"
            echo "checkout-ref=${UPDATE_BRANCH}" >> "$GITHUB_OUTPUT"
          else
            echo "::notice::Checkout: ${{ github.repository }} does not have ref ${UPDATE_BRANCH} (fallback to main)"
            echo "checkout-ref=main" >> "$GITHUB_OUTPUT"
          fi

      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ steps.repo.outputs.checkout-ref }}

      - name: Set up Ruby 4.0.5
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 4.0.5
          bundler-cache: true

      - name: Cache Temporary Data
        uses: actions/cache@v5
        with:
          path: tmp
          key: data-update-cache-${{ github.run_id }}
          restore-keys: |
            data-update-cache-

      - name: Perform Update Rake Task
        run: bundle exec rake update

      - name: Archive Data Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: data-update-artifacts
          path: _data

      - name: Create or Update Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.UPDATE_BRANCH }}
          base: main
          add-paths: _data/**
          commit-message: Apply data updates
          committer: The Hack Different fully sentient AI <41898282+github-actions[bot]@users.noreply.github.com>
          author: The Hack Different fully sentient AI <41898282+github-actions[bot]@users.noreply.github.com>
          title: "Automated Data Update"
          body: "Automated data update from run ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          labels: data-update
